added integration test, and TODO-s
mrbelpit/accenture2020 pull request #42
Opened 2020-06-28 17:56 UTC by mrbelpit

Added test: nem Adminok nem férhetnek hozzá az /admin/ endpointokhoz, TODO-k rakva a metódokhoz amiket megéri tesztelni

2020-06-28 19:59 UTC, szukacs requested changes

2020-06-28 19:59 UTC, szukacs commented on src/main/java/accenture/demo/distance/DistanceServiceImpl.java
> +
I think this is not necessary here

2020-06-28 19:59 UTC, szukacs commented on src/main/java/accenture/demo/admin/AdminExceptionHandler.java
> +  //TODO not tested
Pls. remove TODOs.

2020-06-28 19:59 UTC, szukacs commented on src/main/java/accenture/demo/admin/AdminExceptionHandler.java
> +  //TODO not tested
I added them to Trello

2020-06-29 11:14 UTC, szukacs approved these changes

2020-06-29 11:15 UTC, spiglebach approved these changes

2020-06-29 12:03 UTC, szukacs approved these changes

2020-06-29 12:05 UTC, merged